import * as React from "react";
import Head from "next/head";

export const SiteLayout: React.FC<{children: React.ReactNode}> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Your Site</title>
        <meta name="description" content="Generated by WebCrumbs" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </>
  );
}
